name: Deploy microservices to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy-service1:
    name: Deploy service1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

       # ─── 1) AUTHENTICATE ───────────────────────────────────────────────
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}    

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true         

      - name: Update gcloud components
        run: gcloud components update                         

      - name: Build and deploy service1
        run: |
          # Tải mã nguồn lên Cloud Build
          gcloud builds submit service1 \
                              --gcs-source-staging-dir=gs://aiagent-ezinsight-bucket/aiagent/service1 \
                              --config=service1/cloudbuild.yaml

          # Deploy service lên Cloud Run
          gcloud run deploy service1 \
            --image gcr.io/$PROJECT_ID/service1 \
            --region $REGION \
            --platform managed \
            --timeout 600s \
            --allow-unauthenticated

  deploy-service2:
    name: Deploy service2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

             # ─── 1) AUTHENTICATE ───────────────────────────────────────────────
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}    

      # ─── 2) SETUP GOOGLE CLOUD SDK ───────────────────────────────────────
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true                        

      - name: Update gcloud components
        run: gcloud components update                          

      - name: Build and deploy service2
        run: |
          # gcloud builds submit service2 \
          #   --tag gcr.io/$PROJECT_ID/service2 
          gcloud builds submit service2 \
                              --gcs-source-staging-dir=gs://aiagent-ezinsight-bucket/aiagent/service2 \
                              --config=service2/cloudbuild.yaml

          gcloud run deploy service2 \
            --image gcr.io/$PROJECT_ID/service2 \
            --region $REGION \
            --platform managed \
            --timeout 600s \
            --allow-unauthenticated
